### ISSUE TITLE
Missing instructions in README file?

### ISSUE THREAD

**Issue by p-neves** [specify/specify7-docker#9]
Hi:

In reading the instructions for the docker container install of Specify 7 it seems to be missing the part relating to the Specify 6 local installation. The instructions [here](https://github.com/specify/specify7-docker/tree/sp7_only) mention the fact that one needs to copy the "Specify 6 client into the specify7/specify6_thick_client directory.". Is this not also the case with the present installation?

I'm asking this because when I try to create the docker image with my database (and not the sample one) I still have the sample configs in specify7-docker/specify6_thick_client/config...

Hope I was clear enough...

Cheers:
Pedro

**Comment by maxpatiiuk** [comment]
Hello Pedro,

Copying Specify 6 client is no longer required as the necessary files are provided when you clone the repository.

Those files are required by Specify 7 and should be there even if you choose to use your own database.

-Max

**Comment by p-neves** [comment]
Humm, Ok. But I've tried bulding a Docker image with my database (by copying the sql as database.sql to /data) by the docker image still opens the test DB. I must have done something wrong. I had a previous docker image with your database.sql...

**Comment by maxpatiiuk** [comment]
Docker went though all of the initialization steps (including importing `database.sql`) only once on the first run of the `docker-compose up` command. On the subsequent calls to the same container, it would reuse the volume created in the first iteration, even if you made changes to `database.sql`.

In order to make Docker rebuild your container (and look for changes to files), please run the `docker-compose up` command with the `--build` flag, just like on this picture:
![Screen Shot 2020-10-02 at 9 23 59 PM](https://user-images.githubusercontent.com/40512816/94956955-a9f77e80-04f5-11eb-9052-b7ef974b9080.png)
(the `-d` flag is optional and means that `docker-compose` would run in the background instead of the foreground)

I will make sure to make this more clear in the `README.md`

**Comment by p-neves** [comment]
Ah. OK. Thanks for the explanations.

**Comment by p-neves** [comment]
Max:

I'm sorry to reopen this issue in order to get back to you, but I'm having a few issues with my Specify install and I'd like to know if you have some pointers for me.

I had Specify 6.8 and 7.4 running on a test server (Ubuntu 20.04 LTS) without problems. Now I want to move my institution's DB to that server, but I cannot find any instructions on how to do it. I've e-mailed support@specifysoftware.org but I got no answer so far.

What I did:
1. Backup my institution's database;
2. copy that DB to my server and import this "new" DB into MySQL (I had to create the DB first due to a MySQL [bug)](https://stackoverflow.com/questions/859313/error-importing-sql-dump-into-mysql-unknown-database-cant-create-database):
`mysql -u root -p specify6_4 < backupsSpecify_02102020.sql `
3. Add IT User and Specify Master User and grant them permissions for my DB. (I've used new IT and Master users - not sure if this is correct.
4. Test connections: I can log into my new DB via ssh and remotely with both IT and Master users. I cannot log with users created with specify -- I get the following error:  I get the following error: "Could not create connection to database server. Attempted reconnect 3 times. Giving up. For [jdbc:mysql://192.168.2.186:3306/specify6_4?characterEncoding=UTF-8&autoReconnect=TRUE][admin]". 

Now, I'm kinda stuck on this: I cannot run Specify 6 with my new DB nor can run Specify7 (via Docker container).

Any hints?

Thanks a lot:
Pedro

**Comment by maxpatiiuk** [comment]
What is your MySQL version? As far as I am aware, MySQL 8 is not compatible with Specify and would cause the error message you are getting. Please try version 5.7 instead.
Alternatively, you can use MariaDB. Version 10.4 is fully supported, although other versions may work too.

Also, if this fixes your issue, please respond to the message you sent to support@specifysoftware.org saying that the issue is fixed

**Comment by p-neves** [comment]
I'm using MySQL server 5.7

**Comment by maxpatiiuk** [comment]
This is most likely not a bug, but an issue with the database server or some other software you have installed. For example, which version of Java do you have? Amazon Correto 8 is compatible with Specify 6.8.00
